micronaut:
  application:
    name: music-mashup
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    client:
      read-timeout: 1s
      connect-timeout: 1s
    services:
      musicbrainz:
        url: "http://musicbrainz.org/"
        path: "/ws/2"
      wikidata:
        url: "https://www.wikidata.org"
        path: "/w/api.php"
      wikipedia:
        url: "https://en.wikipedia.org"
        path: "/w/api.php"
      coverart:
        url: "http://coverartarchive.org"
        read-timeout: 2s
        connect-timeout: 2s
        pool:
          enabled: true
          max-connections: 30


